name: Practice

on:
  push:
  workflow_dispatch:

run-name: Gemini excercise

jobs:

  generate_data:
    name: first step
    runs-on: ubuntu-24.04
    outputs:
      secret_word: $ {{ steps.first_job.outputs.word }}
    steps:
      - id: first_job
        name: Set variable here
        run: |
          magic=Matrix

          echo " word=${magic} >> $GITHUB_OUTPUT "

  recieve_data:
    name: second step
    runs-on: ubuntu-24.04
    needs: generate_data
    steps:
      - run: echo " the secret word is ${{ needs.generate_data.outputs.secret_word }} "
      