name: workflow, jobs, steps and names 

run-name: run here

on: 
  pull_request:
  
  workflow_dispatch:

jobs:
  first_jobs:
    runs-on: ubuntu-24.04
    steps:
      - name: genesis
        run: echo "my bitch"
      
      - name: echo "Intro"
        run: echo "Wassup niggas"
    
  second_job:
    runs-on: ubuntu-24.04
    steps:
      - name: neggie
        run: echo "Hello neggies"